### ISSUE TITLE
Enquiry on using the bag of velocyto script for Plasmodium 10X cell ranger BAM

### ISSUE THREAD

**Issue by JesseRop** [xuesoso/bag_of_velocyto#1]
Hi Yuan, 

I was just going through your scRNAseq Toxo paper on Life which is very well presented and highlights very interesting results exemplified by how you followed up on the expression profile of one single cell to identify a transcription factor that you then go on to validate. However, I'm more interested in the RNA velocity analysis as I'm trying to do this on P.Falciparum 10X scRNAseq data. I intend to use the code shared on this github repo for velocyto analysis. I'm relatively new to python and would be grateful for guidance on how to customize the code for cellranger 10X BAM files.

Many thanks,
Jesse

**Comment by xuesoso** [comment]
Hi Jesse,

Thanks for the kind words. bag_of_velocyto is written specifically for SmartSeq2 experiments in mind. For 10X datasets, I would recommend using velocyto's command line function. Look specifically [here](https://velocyto.org/velocyto.py/tutorial/cli.html#run10x-run-on-10x-chromium-samples). Let me know if you have other questions.
